/* Extra copy for the camera-setup feature (ko.setup.* covers the rest). */
export const ss = {
  stageAria: (n: number, ppc: number) => `카메라 미리보기 — ROI ${n}개, ${ppc} px/cm`,
  safeFrame: '안전 영역',
  outOfFrame: 'OUT OF FRAME',
  pausedTitle: '미리보기 일시정지',
  unavailableTitle: '카메라 사용 불가',
  mockLabel: 'MOCK',
  busyJob: '촬영 작업이 진행 중이라 지금은 조작할 수 없습니다',
  exposure: '노출 (µs)', gain: '게인', wb: '화이트밸런스', lens: '렌즈 위치',
  scaleReadout: (ppc: string, cm: number) => `${ppc} px/cm (${cm} cm 기준)`,
  measureOn: '두 점 찍기 (진행 중)', measureOff: '두 점 찍기',
  potNow: (cm: number) => `현재 ${cm} cm`,
  naming: '이름 매기는 중',
  shuffleNeedsEven: '화분 수가 짝수여야 무작위 배정할 수 있습니다',
  shuffleNeedsPots: 'ROI 가 먼저 있어야 합니다',
  noPots: 'ROI 를 먼저 배치하세요',
  treatPick: (pid: string) => `${pid} 처리군`,
  calibThumb: '기준 사진',
  calibNone: '아직 기준 사진이 없습니다',
  driftDx: 'dx', driftDy: 'dy', driftMag: '크기', driftDeg: '회전', driftScale: '배율', driftResp: '응답',
  driftLevel: { ok: '정상', drift: '밀림', fail: '실패', unreliable: '신뢰 불가', unknown: '미확인' } as Record<string, string>,
  driftOff: '기준 사진과 최근 촬영이 모두 있어야 판정합니다',
  centerNow: '지금', centerProposed: '제안',
  centerSrc: (k: string) => `기준 이미지: ${k === 'latest' ? '최근 촬영' : 'calib.jpg'}`,
  centerNoImage: '기준 사진 또는 최근 촬영이 있어야 합니다',
  copy: '복사', copied: '복사됨',
  message: '메시지',
  view: (i: number, n: number) => `${i}/${n}`,
} as const
