/* Extra copy for the capture feature (ko.capture.* covers the rest). */
export const cs = {
  tabs: { capture: '촬영 · LED', setup: '카메라 설정' },
  nextPhase: (p: string) => `다음 단계: ${p}`,
  expected: (d: string, p: string) => `예상 촬영 시각 dawn ${d} · pm ${p}`,
  timer: (active: boolean, next: string | null) => `systemd 타이머 ${active ? '활성' : '비활성'}${next ? ` · 다음 ${next}` : ''}`,
  tz: (tz: string) => `시간대 ${tz}`,
  progress: '진행 상황',
  currentStep: (s: string) => `현재 단계: ${s}`,
  noJob: '실행 중인 작업이 없습니다',
  lastSummary: (phase: string, state: string, when: string) => `마지막 작업 · ${phase} · ${state} · ${when}`,
  warming: '예열 남은 시간',
  cancel: '취소',
  cancelling: '취소 중…',
  running: '촬영 진행 중',
  noLast: '아직 촬영 기록이 없습니다',
  phase: '단계', started: '시작', duration: '소요', rows: '측정 행', trigger: '트리거', state: '상태', published: '발행',
  openFull: '원본 열기 (새 창)',
  imgMissing: '이미지를 불러올 수 없습니다',
  publishError: '발행 오류',
  ledState: 'LED 상태', ledOn: '켜짐', ledOff: '꺼짐', ledPin: 'GPIO 핀', ledWarmup: '예열 (s)', ledDriver: '드라이버', ledReason: '사유',
  ledToggle: 'LED 전원',
  force: '조건 무시 (force)', forceHint: '이미 촬영한 단계·조용한 시간창을 무시하고 실행합니다',
  phaseLabel: '단계 선택',
  replayResult: (sent: number, skipped: number, errs: number) => `보냄 ${sent} · 건너뜀 ${skipped} · 오류 ${errs}`,
  noJobs: '촬영 이력이 없습니다',
  jobDisabled: '촬영이 진행 중입니다',
} as const
